In [1]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn import svm;
from sklearn.linear_model import LinearRegression;
from sklearn.model_selection import train_test_split
from matplotlib import rcParams;

In [2]:
df2019 = pd.read_csv("Jan_2019_ontimeWithNames.csv")
df2020 = pd.read_csv("Jan_2020_ontimeWithNames.csv")
#df2019.head()
#df2020.head()/l

In [3]:
print(set(df2020.columns) == set(df2019.columns))

True

In [4]:
combined = pd.concat([df2019,df2020])
print('Shape:',combined.shape)
#combined.head()

Shape: (1191331, 26)

In [5]:
combined.columns.values.tolist()

['flightid',
 'day_of_month',
 'day_of_week',
 'op_unique_carrier',
 'op_carrier_airline_id',
 'op_carrier',
 'tail_num',
 'op_carrier_fl_num',
 'origin_airport_id',
 'origin_airport_seq_id',
 'origin',
 'dest_airport_id',
 'dest_airport_seq_id',
 'dest',
 'dep_time',
 'dep_del15',
 'dep_time_blk',
 'arr_time',
 'arr_del15',
 'cancelled',
 'diverted',
 'distance',
 'origin_airport',
 'dest_airport',
 'op_carrier_airline',
 'year']

In [6]:
# number of Arilines
combined.op_carrier_airline.nunique()

17

In [7]:
combined.op_carrier_airline.value_counts()

Southwest Airlines             221082
Delta Air Lines                153903
American Airlines              153293
SkyWest Airlines               136086
United Airlines                 95316
Midwest Airlines                54878
American Eagle Airlines         51899
JetBlue Airways                 49152
Comair                          47478
Endeavor Air                    43266
Alaska Airlines, Inc.           41854
Mesa Airlines                   36182
Spirit Airlines                 32699
Atlantic Southeast Airlines     23759
Frontier Airlines               22114
Allegiant Air                   14537
Hawaiian Airlines               13833
Name: op_carrier_airline, dtype: int64

In [8]:
print('Number of :',combined.cancelled.nunique())

Number of : 2

In [9]:
#Cancelled flight indicator 1 = cancelled 0= Not
combined.cancelled.value_counts()

0    1167677
1      23654
Name: cancelled, dtype: int64

In [10]:
cancelledflights = combined[(combined['cancelled']==1)]
cancelledflights.head()

,flightid,day_of_month,day_of_week,op_unique_carrier,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,...,dep_time_blk,arr_time,arr_del15,cancelled,diverted,distance,origin_airport,dest_airport,op_carrier_airline,year
398,399,1,2,AA,19805,AA,N965NN,178,14027,1402702,...,0600-0659,NaN,NaN,1,0,1143,Palm Beach International Airport,O'Hare International Airport,American Airlines,2019
404,405,1,2,AA,19805,AA,N9015D,189,11503,1150305,...,0700-0759,NaN,NaN,1,0,721,Eagle County Regional Airport,Dallas/Fort Worth International Airport,American Airlines,2019
975,976,1,2,OH,20397,OH,N572NN,5103,11057,1105703,...,1900-1959,NaN,NaN,1,0,488,Charlotte Douglas International Airport,Pensacola International Airport,Comair,2019
1979,1980,1,2,EV,20366,EV,N17984,4187,12448,1244807,...,0900-0959,NaN,NaN,1,0,351,Jacksonâ€“Evers International Airport,George Bush Intercontinental Airport,Atlantic Southeast Airlines,2019
1981,1982,1,2,EV,20366,EV,N17984,4189,12266,1226603,...,0700-0759,NaN,NaN,1,0,351,George Bush Intercontinental Airport,Jacksonâ€“Evers International Airport,Atlantic Southeast Airlines,2019

In [11]:
print('Null values:', cancelledflights.isna().sum())

print('+++++++++++++++++++++++++++++++++++++++++++++++++++')
print('cancelledflights Shape:', cancelledflights.shape)

Null values: flightid                     0
day_of_month                 0
day_of_week                  0
op_unique_carrier            0
op_carrier_airline_id        0
op_carrier                   0
tail_num                  3241
op_carrier_fl_num            0
origin_airport_id            0
origin_airport_seq_id        0
origin                       0
dest_airport_id              0
dest_airport_seq_id          0
dest                         0
dep_time                 23016
dep_del15                23054
dep_time_blk                 0
arr_time                 23654
arr_del15                23654
cancelled                    0
diverted                     0
distance                     0
origin_airport               0
dest_airport                 0
op_carrier_airline           0
year                         0
dtype: int64
+++++++++++++++++++++++++++++++++++++++++++++++++++
cancelledflights Shape: (23654, 26)

In [12]:
 cancelledflights.cancelled.value_counts()

1    23654
Name: cancelled, dtype: int64

In [13]:
#New dataframe with cancelled flights removed
newcombined = combined[(combined['cancelled']==0)]
newcombined.head(5)

,flightid,day_of_month,day_of_week,op_unique_carrier,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,...,dep_time_blk,arr_time,arr_del15,cancelled,diverted,distance,origin_airport,dest_airport,op_carrier_airline,year
0,1,1,2,9E,20363,9E,N8688C,3280,11953,1195302,...,0600-0659,722.0,0.0,0,0,300,Gainesville Regional Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019
1,2,1,2,9E,20363,9E,N348PQ,3281,13487,1348702,...,1400-1459,1633.0,0.0,0,0,596,Minneapolisâ€“Saint Paul International Airport (...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019
2,3,1,2,9E,20363,9E,N8896A,3282,11433,1143302,...,1200-1259,1329.0,0.0,0,0,229,Detroit Metropolitan Wayne County Airport,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019
3,4,1,2,9E,20363,9E,N8886A,3283,15249,1524906,...,1500-1559,1625.0,0.0,0,0,223,Tallahassee International Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019
4,5,1,2,9E,20363,9E,N8974C,3284,10397,1039707,...,1900-1959,1940.0,0.0,0,0,579,Hartsfieldâ€“Jackson Atlanta International Airport,Fort Smith Regional Airport,Endeavor Air,2019

In [14]:
#dropping the cancelled column

newcombined = newcombined.drop(['cancelled'], axis = 1)

In [15]:
#Original shape was Shape: (1191331, 26) Removed  23654
print(' Shape:', newcombined.shape)

 Shape: (1167677, 25)

In [16]:
newcombined.head(2)

,flightid,day_of_month,day_of_week,op_unique_carrier,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,...,dep_del15,dep_time_blk,arr_time,arr_del15,diverted,distance,origin_airport,dest_airport,op_carrier_airline,year
0,1,1,2,9E,20363,9E,N8688C,3280,11953,1195302,...,0.0,0600-0659,722.0,0.0,0,300,Gainesville Regional Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019
1,2,1,2,9E,20363,9E,N348PQ,3281,13487,1348702,...,0.0,1400-1459,1633.0,0.0,0,596,Minneapolisâ€“Saint Paul International Airport (...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019

In [17]:
#airport Counts 
airportO = newcombined.origin_airport.nunique()
airportD = newcombined.dest_airport.nunique()

print(airportO, airportD)

353 353

In [18]:
#diverted = delayed
newcombined.diverted.value_counts()

0    1165231
1       2446
Name: diverted, dtype: int64

In [19]:
divertedflights = newcombined[(newcombined['diverted']==1)]
divertedflights.head(2)

,flightid,day_of_month,day_of_week,op_unique_carrier,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,...,dep_del15,dep_time_blk,arr_time,arr_del15,diverted,distance,origin_airport,dest_airport,op_carrier_airline,year
1255,1256,1,2,B6,20409,B6,N613JB,358,10800,1080003,...,0.0,2100-2159,709.0,NaN,1,2465,Bob Hope Airport,John F. Kennedy International Airport,JetBlue Airways,2019
1602,1603,1,2,B6,20409,B6,N184JB,1210,12451,1245102,...,0.0,1200-1259,1810.0,NaN,1,1010,Jacksonville International Airport,Logan International Airport,JetBlue Airways,2019

In [20]:
newcombined = newcombined[(newcombined['diverted']==0)]
newcombined.head(5)

,flightid,day_of_month,day_of_week,op_unique_carrier,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,...,dep_del15,dep_time_blk,arr_time,arr_del15,diverted,distance,origin_airport,dest_airport,op_carrier_airline,year
0,1,1,2,9E,20363,9E,N8688C,3280,11953,1195302,...,0.0,0600-0659,722.0,0.0,0,300,Gainesville Regional Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019
1,2,1,2,9E,20363,9E,N348PQ,3281,13487,1348702,...,0.0,1400-1459,1633.0,0.0,0,596,Minneapolisâ€“Saint Paul International Airport (...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019
2,3,1,2,9E,20363,9E,N8896A,3282,11433,1143302,...,0.0,1200-1259,1329.0,0.0,0,229,Detroit Metropolitan Wayne County Airport,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019
3,4,1,2,9E,20363,9E,N8886A,3283,15249,1524906,...,0.0,1500-1559,1625.0,0.0,0,223,Tallahassee International Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019
4,5,1,2,9E,20363,9E,N8974C,3284,10397,1039707,...,0.0,1900-1959,1940.0,0.0,0,579,Hartsfieldâ€“Jackson Atlanta International Airport,Fort Smith Regional Airport,Endeavor Air,2019

In [21]:
newcombined = newcombined.drop(['diverted'], axis = 1)

In [22]:
newcombined.to_csv('updatedCOMBINED.csv',index=False)

In [23]:
print(' Shape:', newcombined.shape)

 Shape: (1165231, 24)

In [24]:
newcombined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1165231 entries, 0 to 607345
Data columns (total 24 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   flightid               1165231 non-null  int64
 1   day_of_month           1165231 non-null  int64
 2   day_of_week            1165231 non-null  int64
 3   op_unique_carrier      1165231 non-null  object
 4   op_carrier_airline_id  1165231 non-null  int64
 5   op_carrier             1165231 non-null  object
 6   tail_num               1165231 non-null  object
 7   op_carrier_fl_num      1165231 non-null  int64
 8   origin_airport_id      1165231 non-null  int64
 9   origin_airport_seq_id  1165231 non-null  int64
 10  origin                 1165231 non-null  object
 11  dest_airport_id        1165231 non-null  int64
 12  dest_airport_seq_id    1165231 non-null  int64
 13  dest                   1165231 non-null  object
 14  dep_time               1165231 non-null  float64
 15  dep_del15              1165231 non-null  float64
 16  dep_time_blk           1165231 non-null  object
 17  arr_time               1165231 non-null  float64
 18  arr_del15              1165231 non-null  float64
 19  distance               1165231 non-null  int64
 20  origin_airport         1165231 non-null  object
 21  dest_airport           1165231 non-null  object
 22  op_carrier_airline     1165231 non-null  object
 23  year                   1165231 non-null  int64
dtypes: float64(4), int64(11), object(9)
memory usage: 222.3+ MB

In [25]:
#dropping unused columns
data = newcombined.drop(['op_unique_carrier',
 'op_carrier_airline_id',
 'op_carrier',
 'tail_num','origin_airport_id',
 'origin_airport_seq_id','dest_airport_id',
 'dest_airport_seq_id'], axis=1)
data = data.set_index('op_carrier_fl_num')
data.head(2)
#data.to_csv('updatedCOMBINED.csv',index=False)

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,distance,origin_airport,dest_airport,op_carrier_airline,year
op_carrier_fl_num,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,300,Gainesville Regional Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019
3281,2,1,2,MSP,CVG,1359.0,0.0,1400-1459,1633.0,0.0,596,Minneapolisâ€“Saint Paul International Airport (...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1165231 entries, 3280 to 4686
Data columns (total 15 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   flightid            1165231 non-null  int64
 1   day_of_month        1165231 non-null  int64
 2   day_of_week         1165231 non-null  int64
 3   origin              1165231 non-null  object
 4   dest                1165231 non-null  object
 5   dep_time            1165231 non-null  float64
 6   dep_del15           1165231 non-null  float64
 7   dep_time_blk        1165231 non-null  object
 8   arr_time            1165231 non-null  float64
 9   arr_del15           1165231 non-null  float64
 10  distance            1165231 non-null  int64
 11  origin_airport      1165231 non-null  object
 12  dest_airport        1165231 non-null  object
 13  op_carrier_airline  1165231 non-null  object
 14  year                1165231 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 142.2+ MB

In [27]:
data.dep_time_blk.value_counts()

0600-0659    84358
0700-0759    77553
0800-0859    76889
1700-1759    75290
1200-1259    73476
1100-1159    73471
1500-1559    70574
1000-1059    70303
1400-1459    70070
0900-0959    69828
1600-1659    69825
1800-1859    67906
1300-1359    66655
1900-1959    63318
2000-2059    54034
2100-2159    35827
0001-0559    31413
2200-2259    26653
2300-2359     7788
Name: dep_time_blk, dtype: int64

In [28]:
data.dep_time_blk.nunique()

19

In [29]:
#df[['First','Last']] = df.Name.str.split("_",expand=True)
data['dep_time_blk111'] = data['dep_time_blk'].astype(str)

In [32]:
data

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,distance,origin_airport,dest_airport,op_carrier_airline,year,dep_time_blk111
op_carrier_fl_num,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,300,Gainesville Regional Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,0600-0659
3281,2,1,2,MSP,CVG,1359.0,0.0,1400-1459,1633.0,0.0,596,Minneapolisâ€“Saint Paul International Airport (...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1400-1459
3282,3,1,2,DTW,CVG,1215.0,0.0,1200-1259,1329.0,0.0,229,Detroit Metropolitan Wayne County Airport,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1200-1259
3283,4,1,2,TLH,ATL,1521.0,0.0,1500-1559,1625.0,0.0,223,Tallahassee International Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,1500-1559
3284,5,1,2,ATL,FSM,1847.0,0.0,1900-1959,1940.0,0.0,579,Hartsfieldâ€“Jackson Atlanta International Airport,Fort Smith Regional Airport,Endeavor Air,2019,1900-1959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3429,607342,1,3,AUS,FLL,1107.0,1.0,1000-1059,1429.0,0.0,1105,Austinâ€“Bergstrom International Airport,Fort Lauderdaleâ€“Hollywood International Airport,Southwest Airlines,2020,1000-1059
6,607343,1,3,AUS,HOU,539.0,0.0,0001-0559,617.0,0.0,148,Austinâ€“Bergstrom International Airport,William P. Hobby Airport,Southwest Airlines,2020,0001-0559
3432,607344,1,3,AUS,HOU,1251.0,1.0,1200-1259,1335.0,1.0,148,Austinâ€“Bergstrom International Airport,William P. Hobby Airport,Southwest Airlines,2020,1200-1259
4538,607345,1,3,AUS,HOU,845.0,0.0,0800-0859,929.0,0.0,148,Austinâ€“Bergstrom International Airport,William P. Hobby Airport,Southwest Airlines,2020,0800-0859
4686,607346,1,3,AUS,HOU,1744.0,0.0,1700-1759,1839.0,0.0,148,Austinâ€“Bergstrom International Airport,William P. Hobby Airport,Southwest Airlines,2020,1700-1759

In [36]:
data[['dep_time_blkSTART','dep_time_blkEND']] =  data['dep_time_blk111'].str.split("-",expand=True)


data.drop('dep_time_blk111', axis=1, inplace=True)

KeyError: 'dep_time_blk111'

In [ ]:
data['dep_time_blkSTART'] = data



data[['dep_time_blkSTART']] =  data['dep_time_blkSTART'].str.split("-",expand=True)

In [46]:
len(data.dep_time_blkSTART.unique())

19

In [51]:
#getting lenght

data['START length'] = data["dep_time_blkSTART"].str.len()
data['END length'] = data["dep_time_blkEND"].str.len()

In [58]:

data.head(5)

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,distance,origin_airport,dest_airport,op_carrier_airline,year,dep_time_blkSTART,dep_time_blkEND,START length,END length
op_carrier_fl_num,,,,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,300,Gainesville Regional Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3
3281,2,1,2,MSP,CVG,1359.0,0.0,1400-1459,1633.0,0.0,596,Minneapolisâ€“Saint Paul International Airport (...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1400,1459,4,4
3282,3,1,2,DTW,CVG,1215.0,0.0,1200-1259,1329.0,0.0,229,Detroit Metropolitan Wayne County Airport,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1200,1259,4,4
3283,4,1,2,TLH,ATL,1521.0,0.0,1500-1559,1625.0,0.0,223,Tallahassee International Airport,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,1500,1559,4,4
3284,5,1,2,ATL,FSM,1847.0,0.0,1900-1959,1940.0,0.0,579,Hartsfieldâ€“Jackson Atlanta International Airport,Fort Smith Regional Airport,Endeavor Air,2019,1900,1959,4,4

In [65]:
# data['hour'] = data['col'] .str[0:1]
        #data['minute'] = data['col'] 


def splitter(sl,dT):
    
    if sl == 3:
        return dT.str[0:1]
    elif sl == 4:
        return dT.str[0:2]
    
    
   # , x["starting min dep"]

In [73]:
 data['dep_time'].astype(str)

op_carrier_fl_num
3280     601.0
3281    1359.0
3282    1215.0
3283    1521.0
3284    1847.0
         ...
3429    1107.0
6        539.0
3432    1251.0
4538     845.0
4686    1744.0
Name: dep_time, Length: 1165231, dtype: object

In [ ]:

def splitter(sl,dT,sH,sM):
    if sl == 3:
        return sh.str[0:1]; sM.str[2:3]
    elif sl == 4:
        return sh.str[0:2]; sM.str[2:4]

In [74]:
#data[['dep_time_blkSTART']] =  data['dep_time_blkSTART'].str.split("-",expand=True)

data['Dep HOUR']  = data.apply(lambda x:splitter(x["START length"], x["dep_time"]), axis=1)

AttributeError: 'str' object has no attribute 'str'

In [82]:
data.head(1)

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,...,dest_airport,op_carrier_airline,year,dep_time_blkSTART,dep_time_blkEND,START length,END length,col,hour,minute
op_carrier_fl_num,,,,,,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0

In [83]:
data['col'] = data['dep_time_blkSTART'].astype(str) 

data.loc[data['START length'] == 3, 'hour'] = data['col'].str[0:1]
data.loc[data['START length'] == 4, 'hour'] = data['col'].str[0:2]

KeyboardInterrupt:

In [84]:
data.head(5)

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,...,dest_airport,op_carrier_airline,year,dep_time_blkSTART,dep_time_blkEND,START length,END length,col,hour,minute
op_carrier_fl_num,,,,,,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0
3281,2,1,2,MSP,CVG,1359.0,0.0,1400-1459,1633.0,0.0,...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1400,1459,4,4,1400,1,0
3282,3,1,2,DTW,CVG,1215.0,0.0,1200-1259,1329.0,0.0,...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1200,1259,4,4,1200,1,0
3283,4,1,2,TLH,ATL,1521.0,0.0,1500-1559,1625.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,1500,1559,4,4,1500,1,0
3284,5,1,2,ATL,FSM,1847.0,0.0,1900-1959,1940.0,0.0,...,Fort Smith Regional Airport,Endeavor Air,2019,1900,1959,4,4,1900,1,0

In [ ]:
data.loc[data['START length'] == 3, 'minute'] = data['col'].str[2:3]
data.loc[data['START length'] == 4, 'minute'] = data['col'].str[2:4]

In [79]:
d2 = data[(data['START length']== 3)]
d2

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,...,dest_airport,op_carrier_airline,year,dep_time_blkSTART,dep_time_blkEND,START length,END length,col,hour,minute
op_carrier_fl_num,,,,,,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0
3285,6,1,2,DAY,MSP,853.0,0.0,0900-0959,953.0,0.0,...,Minneapolisâ€“Saint Paul International Airport (...,Endeavor Air,2019,900,959,3,3,900,9,0
3290,12,1,2,CAK,ATL,557.0,0.0,0600-0659,737.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0
3297,20,1,2,DTW,CVG,817.0,0.0,0800-0859,932.0,0.0,...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,800,859,3,3,800,8,0
3304,29,1,2,CAE,ATL,807.0,0.0,0800-0859,914.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,800,859,3,3,800,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3691,607322,1,3,AUS,BWI,606.0,0.0,0600-0659,945.0,0.0,...,Baltimore/Washington International Thurgood Ma...,Southwest Airlines,2020,600,659,3,3,600,6,0
1557,607326,1,3,AUS,DAL,644.0,0.0,0600-0659,737.0,0.0,...,Dallas Love Field,Southwest Airlines,2020,600,659,3,3,600,6,0
4990,607328,1,3,AUS,DAL,915.0,0.0,0900-0959,1005.0,0.0,...,Dallas Love Field,Southwest Airlines,2020,900,959,3,3,900,9,0
4683,607339,1,3,AUS,ELP,755.0,0.0,0800-0859,833.0,0.0,...,El Paso International Airport,Southwest Airlines,2020,800,859,3,3,800,8,0
4538,607345,1,3,AUS,HOU,845.0,0.0,0800-0859,929.0,0.0,...,William P. Hobby Airport,Southwest Airlines,2020,800,859,3,3,800,8,0

In [80]:
d2['col'] = d2['dep_time_blkSTART'].astype(str) 

d2['hour'] = d2['col'] .str[0:1]
d2['minute'] = d2['col'] .str[2:3]

<ipython-input-80-b5191f895b74>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d2['col'] = d2['dep_time_blkSTART'].astype(str)
<ipython-input-80-b5191f895b74>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d2['hour'] = d2['col'] .str[0:1]
<ipython-input-80-b5191f895b74>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d2['minute'] = d2['col'] .str[2:3]

In [81]:
d2

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,...,dest_airport,op_carrier_airline,year,dep_time_blkSTART,dep_time_blkEND,START length,END length,col,hour,minute
op_carrier_fl_num,,,,,,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0
3285,6,1,2,DAY,MSP,853.0,0.0,0900-0959,953.0,0.0,...,Minneapolisâ€“Saint Paul International Airport (...,Endeavor Air,2019,900,959,3,3,900,9,0
3290,12,1,2,CAK,ATL,557.0,0.0,0600-0659,737.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0
3297,20,1,2,DTW,CVG,817.0,0.0,0800-0859,932.0,0.0,...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,800,859,3,3,800,8,0
3304,29,1,2,CAE,ATL,807.0,0.0,0800-0859,914.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,800,859,3,3,800,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3691,607322,1,3,AUS,BWI,606.0,0.0,0600-0659,945.0,0.0,...,Baltimore/Washington International Thurgood Ma...,Southwest Airlines,2020,600,659,3,3,600,6,0
1557,607326,1,3,AUS,DAL,644.0,0.0,0600-0659,737.0,0.0,...,Dallas Love Field,Southwest Airlines,2020,600,659,3,3,600,6,0
4990,607328,1,3,AUS,DAL,915.0,0.0,0900-0959,1005.0,0.0,...,Dallas Love Field,Southwest Airlines,2020,900,959,3,3,900,9,0
4683,607339,1,3,AUS,ELP,755.0,0.0,0800-0859,833.0,0.0,...,El Paso International Airport,Southwest Airlines,2020,800,859,3,3,800,8,0
4538,607345,1,3,AUS,HOU,845.0,0.0,0800-0859,929.0,0.0,...,William P. Hobby Airport,Southwest Airlines,2020,800,859,3,3,800,8,0

In [75]:


data['col'] = data['dep_time_blkSTART'].astype(str) 

data['hour'] = data['col'] .str[0:1]
data['minute'] = data['col'] .str[2:3]

In [76]:
data

,flightid,day_of_month,day_of_week,origin,dest,dep_time,dep_del15,dep_time_blk,arr_time,arr_del15,...,dest_airport,op_carrier_airline,year,dep_time_blkSTART,dep_time_blkEND,START length,END length,col,hour,minute
op_carrier_fl_num,,,,,,,,,,,,,,,,,,,,,
3280,1,1,2,GNV,ATL,601.0,0.0,0600-0659,722.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,600,659,3,3,600,6,0
3281,2,1,2,MSP,CVG,1359.0,0.0,1400-1459,1633.0,0.0,...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1400,1459,4,4,1400,1,0
3282,3,1,2,DTW,CVG,1215.0,0.0,1200-1259,1329.0,0.0,...,Cincinnati/Northern Kentucky International Air...,Endeavor Air,2019,1200,1259,4,4,1200,1,0
3283,4,1,2,TLH,ATL,1521.0,0.0,1500-1559,1625.0,0.0,...,Hartsfieldâ€“Jackson Atlanta International Airport,Endeavor Air,2019,1500,1559,4,4,1500,1,0
3284,5,1,2,ATL,FSM,1847.0,0.0,1900-1959,1940.0,0.0,...,Fort Smith Regional Airport,Endeavor Air,2019,1900,1959,4,4,1900,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3429,607342,1,3,AUS,FLL,1107.0,1.0,1000-1059,1429.0,0.0,...,Fort Lauderdaleâ€“Hollywood International Airport,Southwest Airlines,2020,1000,1059,4,4,1000,1,0
6,607343,1,3,AUS,HOU,539.0,0.0,0001-0559,617.0,0.0,...,William P. Hobby Airport,Southwest Airlines,2020,1,559,1,3,1,1,
3432,607344,1,3,AUS,HOU,1251.0,1.0,1200-1259,1335.0,1.0,...,William P. Hobby Airport,Southwest Airlines,2020,1200,1259,4,4,1200,1,0
4538,607345,1,3,AUS,HOU,845.0,0.0,0800-0859,929.0,0.0,...,William P. Hobby Airport,Southwest Airlines,2020,800,859,3,3,800,8,0
4686,607346,1,3,AUS,HOU,1744.0,0.0,1700-1759,1839.0,0.0,...,William P. Hobby Airport,Southwest Airlines,2020,1700,1759,4,4,1700,1,0

In [44]:
data['dep_time_blkSTART'] = data['dep_time_blkSTART'].astype(str)
data['dep_time_blkEND'] = data['dep_time_blkEND'].astype(str)
#data['dep_time_blkSTART'] = data['dep_time_blkSTART'].astype(int)
#data['dep_time_blkEND'] = data['dep_time_blkEND'].astype(int)

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1165231 entries, 3280 to 4686
Data columns (total 17 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   flightid            1165231 non-null  int64
 1   day_of_month        1165231 non-null  int64
 2   day_of_week         1165231 non-null  int64
 3   origin              1165231 non-null  object
 4   dest                1165231 non-null  object
 5   dep_time            1165231 non-null  float64
 6   dep_del15           1165231 non-null  float64
 7   dep_time_blk        1165231 non-null  object
 8   arr_time            1165231 non-null  float64
 9   arr_del15           1165231 non-null  float64
 10  distance            1165231 non-null  int64
 11  origin_airport      1165231 non-null  object
 12  dest_airport        1165231 non-null  object
 13  op_carrier_airline  1165231 non-null  object
 14  year                1165231 non-null  int64
 15  dep_time_blkSTART   1165231 non-null  object
 16  dep_time_blkEND     1165231 non-null  object
dtypes: float64(4), int64(5), object(8)
memory usage: 160.0+ MB

In [ ]:
data.to_csv('data.csv',index=False)

In [ ]:
data.drop(['dep_time_delay'], axis = 1)

In [ ]:
data.dep_time.value_counts()

In [ ]:
def dep_time_delay(x,y,z):
    if x >= y and x <= z:
        return 0
    elif x <= y:
        return (x-y) + 40
    elif x >= z:
        return x-z

In [ ]:

data["dep_time_delay"] = data.apply(lambda x:dep_time_delay(x["dep_time"], x["dep_time_blkSTART"], x["dep_time_blkEND"]), axis=1)


#dep_time_delay(data["dep_time"],data["dep_time_blkSTART"],data["dep_time_blkEND"]).apply(lambda x:


#data["dep_time_delay"] = data[["dep_time","dep_time_blkSTART","dep_time_blkEND"]].apply(dep_time_delay, axis=1)

#data["dep_time_delay"] = dep_time_delay(data["dep_time"],data["dep_time_blkSTART"],data["dep_time_blkEND"])

In [ ]:
data

In [ ]:
data.dep_time_delay.value_counts()

In [ ]:
flights = data[(data['dep_time_delay']>0 and <100)]
flights

In [ ]:
flights.dep_time_delay.value_counts()

In [ ]:
flights.query('dep_time_delay >0   &  dep_time_delay< 100')

In [ ]:
flights.query('dep_time_delay > 100')

In [ ]:
=IF(AND(F4>=P4,F4<=Q4),F4-P4,"0")

In [ ]:
def arr_time(x):
    if x >= 600 and x <= 659:
        return '0600-0659'
    elif x>=1400 and x<=1459:
        return '1400-1459'
    elif x>=1200 and x<=1259:
        return '1200-1259'
    elif x>=1500 and x<=1559:
        return '1500-1559'
    elif x>=1900 and x<=1959:
        return '1900-1959'
    elif x>=900 and x<=959:
        return '0900-0959'
    elif x>=1000 and x<=1059:
        return  '1000-1059'
    elif x>=2000 and x<=2059:
        return '2000-2059'
    elif x>=1300 and x<=1359:
        return '1300-1359'
    elif x>=1100 and x<=1159:
        return '1100-1159'
    elif x>=800 and x<=859:
        return '0800-0859'
    elif x>=2200 and x<=2259:
        return '2200-2259'
    elif x>=1600 and x<=1659:
        return '1600-1659'
    elif x>=1700 and x<=1759:
        return '1700-1759'
    elif x>=2100 and x<=2159:
        return '2100-2159'
    elif x>=700 and x<=759:
        return '0700-0759'
    elif x>=1800 and x<=1859:
        return '1800-1859'
    elif x>=1 and x<=559:
        return '0001-0559'
    elif x>=2300 and x<=2400:
        return '2300-2400'
    elif x==0:
        return '0000-0000'

In [ ]:
#Count of how many flights in total
print(data.shape)

In [ ]:
data.isna().sum()

In [ ]:
#No arrival time because the flight has been cancelled 
data.query("arr_time <=0 & cancelled == 0")

In [ ]:
data.query("dep_time <= 0 & cancelled == 1")

In [ ]:
#confirms that all flights that have an arrival delay are either diverted or cancelled 
#data.query('arr_del15 <0 | arr_del15 != arr_del15 & cancelled == 1 & diverted == 1')
data.query('arr_del15 != arr_del15 & cancelled == 1 & diverted == 1')

In [ ]:
data.query('dep_del15 != dep_del15  &  cancelled == 0 & diverted == 0')

In [ ]:

data.query('cancelled == 1 | diverted == 1 & dep_del15 != dep_del15')

In [ ]:
data[data['dep_del15'].isnull()]

In [ ]:
#all null departure delays are cancelled flights. 
data.query('dep_del15.isnull() & cancelled == 0',engine='python')

In [ ]:
data.query('dep_time.isnull() & cancelled == 0',engine='python')

In [ ]:
#Confirms that Arrival Delay is either due to Cancelled or Flighted is diverted
data.query('arr_del15.isnull() & cancelled == 0 & diverted ==0',engine='python')

In [ ]:
data[data['arr_del15'].isnull()]

In [ ]:
#Creating new dataframe without null departure delay values 
new_df= data.query('dep_del15 == dep_del15')
new_df

In [ ]:
new_df.to_csv('updatedCOMBINED.csv',index=False)

In [ ]:
new_df.isna().sum()

In [ ]:


f, (ax,ax1) = plt.subplots(1,2, figsize=(12,6))
dep = sns.countplot(data['dep_del15'], ax=ax)
dep.set_title('Depatures')
dep.set_xlabel('Labels')
dep.set_ylabel('Freq')

arr = sns.countplot(data['arr_del15'], ax=ax1)
arr.set_title('Arrivals')
arr.set_xlabel('Labels')
arr.set_ylabel('Freq')

In [ ]:
f, (ax,ax1) = plt.subplots(1,2, figsize=(12,6))
dep = sns.countplot(new_df['dep_del15'], ax=ax)
dep.set_title('Depatures')
label = dep.set_xlabel('Departure Indicator')
dep.set_ylabel('Frequency')

arr = sns.countplot(new_df['arr_del15'], ax=ax1)
arr.set_title('Arrivals ')
arr.set_xlabel('Arrivals Indicator')
arr.set_ylabel('Frequency')

ax.legend([line1, line2], ['1 =Delay Indicator', 'label2'])

In [ ]:
new_df

In [ ]:
#from matplotlib import rcParams


airlineC = new_df.groupby(['op_carrier_airline']).sum()[['dep_del15']]

rcParams['figure.figsize'] = 40 ,15.27
ax = sns.barplot(x='op_carrier_airline', y='dep_del15', data=airlineC.reset_index())

In [ ]:
airlineC = new_df[(new_df.groupby(['op_carrier_airline']).sum()[['dep_del15']])]

airlineCC = airlineC.all()

exercise = sns.load_dataset(airlineC)


g = sns.catplot(x='op_carrier_airline', y= 'arr_del15',
                hue="smoker", col="year",
                data=exercise, kind="bar",
                height=4, aspect=.7);

In [ ]:
airlineC